# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lganti
repository: https://github.com/lahariganti.github.io
url: https://lahariganti.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark # choices are: 'dark', 'standard', 'markdown'

# Customizations
email: gplahari@gmail.com

navigation:
  - text: home
    url: /index
  - text: whoami
    url: /whoami
  - text: cross-network
    url: /blob

ios_navigation:
  - text: home
    url: /index

permalink: /404.html

esp32:
  - name: ESP32LEDBlink
    server: https://github.com/lahariganti/ESP32LEDBlink/tree/master/ESP32LEDBlinkGATTServer
    client: https://github.com/lahariganti/ESP32LEDBlink/tree/master/ESP32LEDBlink
    description: GATT server & iOS client
    demo: 

social:
  - service: github
    username: lahariganti
    link: https://github.com/lahariganti
  - service: twitter
    username: lahariganti
    link: https://twitter.com/lahariganti

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-assets
  - bootstrap-sass
  - uglifier

