title: Lahari Ganti
repository: https://github.com/lahariganti.github.io
url: https://lahariganti.github.io 

markdown: kramdown

sass:
  style: compressed

theme_mode: dark 

email: gplahari@gmail.com

navigation:
  - text: home
    url: /index
  - text: whoami
    url: /whoami
  - text: cross-network
    url: /blob

ios_navigation:
  - text: home
    url: /index

permalink: /404.html

esp32:
  - name: ESP32LEDBlink
    server: https://github.com/lahariganti/ESP32LEDBlink/tree/master/ESP32LEDBlinkGATTServer
    client: https://github.com/lahariganti/ESP32LEDBlink/tree/master/ESP32LEDBlink
    description: GATT server & iOS client
    demo: 

social:
  - service: github
    username: lahariganti
    link: https://github.com/lahariganti
  - service: twitter
    username: lahariganti
    link: https://twitter.com/lahariganti

gems:
  - jekyll-seo-tag
  - jekyll-assets
  - bootstrap-sass
  - uglifier

