# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lganti
repository: https://github.com/lahariganti.github.io
url: https://lahariganti.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark # choices are: 'dark', 'standard', 'markdown'

# Customizations
email: gplahari@gmail.com

navigation:
  - text: home
    url: /index
  - text: whoami
    url: /whoami

ios_navigation:
  - text: home
    url: /index

permalink: /404.html

onappstore:
  - name: gotta
    description: RealmSwift, ChameleonFramework, SwipeCellKit
    url: https://github.com/lahariganti/gotta
    image: gotta
    details: a to do list app that uses Realm CRUD
    privacy_policy: We don't collect any data. Hence we do not store any data. 

notonappstore:
  - name: isItColdOutside
    description: CLLocation, openweather API
    url: https://github.com/lahariganti/isItColdOutside
    image: isItColdOutside
    details: should i bring a jacket?
  - name: chat
    description: Firebase
    url: https://github.com/lahariganti/chat
    image: chat
    details: uses Firebase relatime database
  - name: diceIT
    description: SceneKit, ARKit
    url: https://github.com/lahariganti/diceIT
    image: dice
    details: roll a dice in AR, woah
  - name: howLong
    description: SceneKit, ARKit
    url: https://github.com/lahariganti/howLong
    image: long
    details: measure in AR, woah
  - name: 3DPokemon
    description: SceneKit, ARKit
    url: https://github.com/lahariganti/3DPokemon
    image: pokemon
    details: see your favorite pokemon in 3D
  - name: notHotdog
    description: CoreML, Vision
    url: https://github.com/lahariganti/notHotdog
    image: hotdog
    details: image recognition app
  - name: whatFlower
    description: CoreML, CreateML, Vision
    url: https://github.com/lahariganti/whatFlower
    image: flower
    details: image recognition app

webapps:
  - name: furierit
    description: automate trading
    url: https://github.com/lahariganti/furierit
    image: https://images.unsplash.com/photo-1518186285589-2f7649de83e0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80
    details: Ruby & R on Rails

music:
  - name: commensalism
    url: https://www.youtube.com/embed/r564NatJhIY

  - name: suitcase
    url: https://www.youtube.com/embed/uIPkSdZAoSo

  - name: sound of rain 
    url: https://www.youtube.com/embed/osnesslvDqo

  - name: Oakland, CA, USA
    url: https://www.youtube.com/embed/nl7KPn6dDSg


social:
  - service: github
    username: lahariganti
    link: https://github.com/lahariganti
  - service: twitter
    username: lahariganti
    link: https://twitter.com/lahariganti



# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-assets
  - bootstrap-sass
  - uglifier

